<?php
$title = 'Editar Pedido';
$this->headTitle($title);
?>
<?php
$form = $this->pedidoForm;
$form->setAttribute('action', $this->url('pedido', array('action' => 'edit','id' => $pedido->getId())));
$form->get('submit')->setAttribute('value', 'Enviar');
$formLabel = $this->plugin('formLabel');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')->setValue($pedido->getId()));?>
<?php echo $this->formHidden($form->get('vendedor'));?>
<?php echo $this->formHidden($form->get('estatus'));?>
<?php echo $this->formHidden($form->get('idalmacen'));?>

<div class="row well well-sm">
    <div class="col-sm-6 col-md-6">
        <h4><?php echo $this->formRow($form->get('codigo'));?></h4>
    </div>
    <div class="col-sm-6 col-md-6 text-right">
        <h4><?php echo $this->formRow($form->get('cliente'));?></h4>
    </div>
</div>

<div class="container-fluid">
    <div class="row content">

        <div class="col-sm-3 sidenav">
            <div class="row text-center">
                <div class="panel panel-primary">

                    <div class="panel-heading">
                        <h3 class="panel-title">Items</h3>
                    </div>

                    <div class="panel-body text-center">
                        <div class="list-group">
                            <?php $total = 0;?>
                                <?php foreach ($items as $item ): ?>
                                    <a href="<?php echo $this->url('item', array('action'=>'edit', 'pedido' => $item->getPedido(), 'producto' => $item->getProducto()));?>" class="list-group-item">
                                        <span class="badge">Subtotal: <br><?php echo $item->getSubtotal(); ?> BsF</span>
                                        <p class="text-left"><?php echo $item->getCantidad(); ?> <?php echo $item->getUnidmedprod(); ?> de <?php echo $item->getNombproducto(); ?></p>
                                    </a>
                                <?php $total = $total + (int) $item->getSubtotal(); ?>
                            <?php endforeach ?>
                        </div>
                    </div>

                    <div class="panel-footer"><h4><?php echo $this->formRow($form->get('preciototal')->setValue($total));?></h4></div>

                </div>
            </div>
        </div>

        <div class="col-sm-9">
            <div class="panel panel-primary">

                <div class="panel-heading">
                    <h3 class="panel-title">

                        <div class="row">
                            <div class="col-sm-2 col-md-2">
                                <h3>Seleccione Categoría</h3>
                            </div>

                            <div class="col-sm-10 col-md-10">

                                <div class="btn-group" >
                                    <input type="submit" class="btn btn-primary" name="selcat" value="Todos" />
                                    <input type="hidden" name="Todos" value="0" />
                                    <?php foreach ($categorias as $categoria ): ?>
                                        <input type="hidden" name="<?php echo $categoria->getNombre() ?>" value="<?php echo $categoria->getId() ?>" />
                                        <input type="submit" class="btn btn-info" name="selcat" value="<?php echo $categoria->getNombre() ?>" />
                                    <?php endforeach ?>
                                </div>
                            </div>
                        </div>
                </div>


                <div class="panel-body text-center">
                    <div class="row">
                        <div class="col-sm-4 col-md-4"><h3>Productos Disponibles</h3></div>
                        <div class="col-sm-8 col-md-8">
                            <?php echo $this->paginationControl($this->paginator,'sliding','partial/paginator-parameter.phtml',array('route' => 'pedido', 'parameters' =>array('action' => 'edit','id' => $pedido->getId()) )); ?>
                        </div>

                    </div>
                    <div class="row well well-sm" >
                        <?php foreach ($paginator as $producto ): ?>
                            <div class="col-sm-4 col-md-3 producto">
                                <a href="<?php echo $this->url('item', array('action'=>'add', 'pedido' => $pedido->getId(), 'producto' => $producto->getId()));?>" class="thumbnail box" >
                                    <?php if (($producto->getModificado() !== '0000-00-00') && (((floor(abs(strtotime($producto->getModificado())-strtotime(date('Y-m-d')))))/86400) < 5)) :?>
                                        <div class="ribbon orange"><span>Actualizado</span></div>
                                    <?php endif ?>
                                    <?php if ($producto->getDisponible() !== '1')  :?>
                                        <div class="ribbon red"><span>Agotado</span></div>
                                    <?php endif ?>
                                        <img src="<?= $producto->getImagen() ?>" alt="<?= $producto->getNombre() ?>" >
                                        <div class="caption">
                                            <h4 id="producto<?= $producto->getId() ?>"><?= $producto->getNombre() ?></h4>
                                            <p>Precio:<?= $producto->getPreciounidad() ?> BsF por  <?= $producto->getNombunidmedventas() ?></p>
                                        </div>
                                </a>
                            </div>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="row well well-sm">
    <div class="col-sm-6 col-md-6">
        <h3><?php echo $this->formRow($form->get('msgventas'));?></h3>
    </div>
    <div class="col-sm-6 col-md-6 text-right">
        <div class="btn-toolbar" role="toolbar" >
            <div class="btn-group pull-left" role="group" >
                <a href="<?php echo $this->url('pedido', array('action'=>'delete', 'id' => $pedido->getId()));?>" class="btn btn-danger">Eliminar Pedido</a>
            </div>
            <div class="btn-group" role="group" >
                <a href="<?php echo $this->url('pedido') ?>" class="btn btn-primary">Listado de Pedidos</a>
            </div>
            <div class="btn-group pull-right" role="group" >
                <?php echo $this->formInput($form->get('submit')->setAttributes(array('class'=> 'btn btn-info', 'value' => 'Guardar'))); ?>
                <?php echo $this->formInput($form->get('submit')->setAttributes(array('class'=> 'btn btn-success', 'value' => 'Enviar'))); ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>