<div class="row well">
    <div class="col-sm-6 col-md-6">
        <h3>Código del Pedido: <td><?php echo $pedido->getCodigo(); ?></h3>
    </div>
    <div class="col-sm-6 col-md-6 text-right">
        <h3>Cliente: <td><?php echo $pedido->getCliente(); ?></h3>
    </div>
</div>

<div class="container-fluid">
    <div class="row content">

        <div class="col-sm-3 sidenav">
            <div class="row text-center">
                <h3>Items</h3>
            </div>
            <div class="well">
                <?php $total = 0;?>
                <?php foreach ($items as $item ): ?>
                    <div>
                        <p><?php echo $item->getCantidad(); ?> <?php echo $item->getUnidmedprod(); ?> de <?php echo $item->getNombproducto(); ?></p>
                        <p class="text-right">Subtotal: <?php echo $item->getSubtotal(); ?> BsF.</p>
                        <br>
                    </div>
                    <?php $total = $total + (int) $item->getSubtotal(); ?>
                <?php endforeach ?>
            </div>
            <h2 class="text-right">Total: <?php echo $total;?> BsF</h2>
        </div>

        <div class="col-sm-9">

            <div class="row text-center">
                <h3>Seleccione el Producto</h3>
            </div>

            <div class="row well" style="display:flex; flex-wrap: wrap;">
                <?php foreach ($productos as $producto ): ?>
                    <div class="col-sm-4 col-md-3">
                        <a href="<?php echo $this->url('item', array('action'=>'add', 'pedido' => $pedido->getId(), 'producto' => $producto->getId()));?>">
                            <div class="thumbnail" style="width:200px; height:150px">
                                <img src="<?= $producto->getImagen() ?>" alt="<?= $producto->getNombre() ?>" style="width:50%; height:auto">
                                <div class="caption">
                                    <h4 id="producto<?= $producto->getId() ?>"><?= $producto->getNombre() ?></h4>
                                    <p>Precio:<?= $producto->getPreciounidad() ?> BsF por  <?= $producto->getUnidadmedidaventas() ?></p>

                                </div>
                            </div>
                        </a>
                    </div>
                <?php endforeach ?>
            </div>

        </div>

    </div>
</div>

<div class="row well">
    <div class="col-sm-6 col-md-6">
        <h2>Estatus: <td><?php echo $pedido->getMsgclientes(); ?></h2>
    </div>
    <div class="col-sm-6 col-md-6 text-right">
        <button class="btn btn-default btn-lg">Enviar</button>
    </div>
</div>