<?php
$title = 'Listado de Pedidos';
$this->headTitle($title);
?>



<div class="panel panel-default">
    <div class="panel-heading">Pedidos</div>
    <div class="panel-body">
        <!-- List group -->
        <div class="list-group">
            <?php foreach ($pedidos as $pedido): ?>
                <a href="<?php echo $this->url('item', array('pedido' => $pedido->getId()));?>" class="list-group-item">
                    <div class="row">
                        <div class="col-sm-6 col-md-2">
                            Fecha: <?php echo $pedido->getFecha(); ?><br>
                            Hora: <?php echo $pedido->getHora(); ?>
                        </div>


                        <div class="col-sm-6 col-md-8 text-center text-primary well well-sm">
                            <strong>Pedido: <?php echo $pedido->getCodigo(); ?> Cliente: <?php echo $pedido->getCliente(); ?> <br>
                            Estatus: <?php echo $pedido->getMsgclientes(); ?></strong>
                        </div>


                        <div class="col-sm-6 col-md-2">
                            Tomado por: <?php echo $pedido->getNombvendedor(); ?><br>
                            Atendido por: <?php echo $pedido->getNombdespachador(); ?>
                        </div>
                    </div>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
</div>



