<?php
$title = 'Despacho';
$this->headTitle($title);
?>


<div class="container">
    <div class="row">
        <div class="col-sm-4 col-md-4">

            <div class="panel panel-primary">
                <div class="panel-heading text-center"><h4>Pedidos en Cola</h4></div>
                <div class="panel-body">
                        <ul class="list-group">
                            <?php foreach ($pedidos as $pedido): ?>
                                        <li class="list-group-item text-center text-primary well">
                                            Pedido: <?php echo $pedido->getCodigo(); ?> <br>
                                                Cliente: <?php echo $pedido->getCliente(); ?>
                                            <?php $url = $this->url('despacho') ?>
                                            <form id="form<?= $pedido->getId() ?>" action="<?php echo $url; ?>" method="post">
                                                <input type="hidden" name="idpedido" value="<?= $pedido->getId() ?>">
                                                <input type="hidden" name="idpedido1" value="<?= $this->idpedido1 ?>">
                                                <input type="hidden" name="idpedido2" value="<?= $this->idpedido2 ?>">
                                                <input type="hidden" name="panel1" value="<?= $this->panel1 ?>">
                                                <input type="hidden" name="panel2" value="<?= $this->panel2 ?>">
                                                <input type="submit" name="submit" value="Atender">
                                            </form>
                                        </li>

                            <?php endforeach; ?>
                        </ul>
                </div>
            </div>

        </div>

        <div class="col-sm-8 col-md-8">
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <?php if (isset($pedido1) && $panel1 === 'Ocupado') : ?>
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <div class="row">

                                    <div class="col-sm-6 col-md-8 text-center text-uppercase ">
                                        <strong>Pedido: <?php echo $pedido1->getCodigo(); ?> <br>
                                            Cliente: <?php echo $pedido1->getCliente(); ?></strong>
                                    </div>

                                    <div class="col-sm-6 col-md-4">
                                        <strong>Precio Total: <?php echo $pedido1->getPreciototal(); ?></strong>
                                    </div>
                                </div>
                            </div>

                            <div class="panel-body">
                                <div class="list-group">
                                    <?php foreach ($items1 as $item1): ?>
                                        <a href="#" class="list-group-item">
                                            <span class="badge">Subtotal: <br><?php echo $item1->getSubtotal(); ?> BsF</span>
                                            <p class="text-left"><?php echo $item1->getCantidad(); ?> <?php echo $item1->getUnidmedprod(); ?> de <?php echo $item1->getNombproducto(); ?></p>
                                        </a>

                                    <?php endforeach; ?>
                                </div>
                            </div>

                            <div class="panel-footer">
                                <div class="row">
                                    <?php $urlpanel1 = $this->url('despacho') ?>
                                    <form id="form-panel1" action="<?php echo $urlpanel1; ?>" method="post">
                                        <input type="hidden" name="idpedido" value="<?= $pedido->getId() ?>">
                                        <input type="hidden" name="idpedido1" value="<?= $this->idpedido1 ?>">
                                        <input type="hidden" name="idpedido2" value="<?= $this->idpedido2 ?>">
                                        <input type="hidden" name="panel1" value="<?= $this->panel1 ?>">
                                        <input type="hidden" name="panel2" value="<?= $this->panel2 ?>">
                                        <input type="hidden" name="idfinalizado" value="panel1">
                                        <input type="submit" name="submit" value="Finalizar">
                                    </form>
                                    </div>
                            </div>
                        </div>

                    <?php endif ?>
                </div>

                <div class="col-sm-6 col-md-6">
                    <?php if (isset($pedido2) && $panel2 === 'Ocupado') : ?>
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <div class="row">

                                    <div class="col-sm-6 col-md-8 text-center text-uppercase ">
                                        <strong>Pedido: <?php echo $pedido2->getCodigo(); ?> <br>
                                            Cliente: <?php echo $pedido2->getCliente(); ?></strong>
                                    </div>

                                    <div class="col-sm-6 col-md-4">
                                        <strong>Precio Total: <?php echo $pedido2->getPreciototal(); ?></strong>
                                    </div>
                                </div>
                            </div>

                            <div class="panel-body">
                                <div class="list-group">
                                    <?php foreach ($items2 as $item2): ?>
                                        <a href="#" class="list-group-item">
                                            <span class="badge">Subtotal: <br><?php echo $item2->getSubtotal(); ?> BsF</span>
                                            <p class="text-left"><?php echo $item2->getCantidad(); ?> <?php echo $item2->getUnidmedprod(); ?> de <?php echo $item2->getNombproducto(); ?></p>
                                        </a>

                                    <?php endforeach; ?>
                                </div>
                            </div>

                            <div class="panel-footer">
                                <div class="row">
                                    <?php $urlpanel2 = $this->url('despacho') ?>
                                    <form id="form-panel2" action="<?php echo $urlpanel2; ?>" method="post">
                                        <input type="hidden" name="idpedido" value="<?= $pedido->getId() ?>">
                                        <input type="hidden" name="idpedido1" value="<?= $this->idpedido1 ?>">
                                        <input type="hidden" name="idpedido2" value="<?= $this->idpedido2 ?>">
                                        <input type="hidden" name="panel1" value="<?= $this->panel1 ?>">
                                        <input type="hidden" name="panel2" value="<?= $this->panel2 ?>">
                                        <input type="hidden" name="idfinalizado" value="panel2">
                                        <input type="submit" name="submit" value="Finalizar">
                                    </form>
                                </div>
                            </div>
                        </div>

                    <?php endif ?>
                </div>
            </div>
        </div>

    </div>
</div>





