<?php
$title = 'Despacho';
$this->headTitle($title);
?>


<div class="container">
    <div class="row">
        <div class="col-sm-4 col-md-4">

            <div class="panel panel-primary">
                <div class="panel-heading text-center"><h4>Pedidos en Cola</h4></div>
                <div class="panel-body">
                        <ul class="list-group">
                            <?php foreach ($pedidos as $pedido): ?>
                                        <li class="list-group-item text-center text-primary well">
                                            Pedido: <?php echo $pedido->getCodigo(); ?> <br>
                                                Cliente: <?php echo $pedido->getCliente(); ?>
                                            <?php $url = $this->url('despacho') ?>
                                            <form name="form" id="form" action="<?php echo $url; ?>" method="post">
                                                <input type="hidden" name="idpedido" value="<?= $pedido->getId() ?>">
                                                <input type="hidden" name="idpedido1" value="<?= $this->idpedido1 ?>">
                                                <input type="hidden" name="idpedido2" value="<?= $this->idpedido2 ?>">
                                                <input type="hidden" name="idpedido3" value="<?= $this->idpedido3 ?>">
                                                <input type="hidden" name="idpedido4" value="<?= $this->idpedido4 ?>">
                                                <input type="hidden" name="panel1" value="<?= $this->panel1 ?>">
                                                <input type="hidden" name="panel2" value="<?= $this->panel2 ?>">
                                                <input type="hidden" name="panel3" value="<?= $this->panel3 ?>">
                                                <input type="hidden" name="panel4" value="<?= $this->panel4 ?>">
                                                <?php if (!empty($despachadores[0])): ?>
                                                <input type="submit" name="submit" id="applybutton" class="btn btn-sm btn-success" value="<?php echo $despachadores[0]; ?>">
                                                <?php endif ?>
                                                <?php if (!empty($despachadores[1])): ?>
                                                    <input type="submit" name="submit" id="applybutton" class="btn btn-sm btn-info" value="<?php echo $despachadores[1]; ?>">
                                                <?php endif ?>
                                                <?php if (!empty($despachadores[2])): ?>
                                                    <input type="submit" name="submit" id="applybutton" class="btn btn-sm btn-warning" value="<?php echo $despachadores[2]; ?>">
                                                <?php endif ?>
                                                <?php if (!empty($despachadores[3])): ?>
                                                    <input type="submit" name="submit" id="applybutton" class="btn btn-sm btn-danger" value="<?php echo $despachadores[3]; ?>">
                                                <?php endif ?>



                                            </form>
                                        </li>

                            <?php endforeach; ?>
                        </ul>
                </div>
            </div>

        </div>

        <div class="col-sm-8 col-md-8">
            <div class="row">

                <div class="col-sm-6 col-md-6">
                    <?php if (isset($pedido1) && $panel1 === 'Ocupado') : ?>
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <div class="row">

                                    <div class="col-sm-6 col-md-8 text-center text-uppercase ">
                                        <strong>Pedido: <?php echo $pedido1->getCodigo(); ?> <br>
                                            Cliente: <?php echo $pedido1->getCliente(); ?></strong>
                                    </div>

                                    <div class="col-sm-6 col-md-4">
                                        <strong>Precio Total: <?php echo $pedido1->getPreciototal(); ?></strong>
                                    </div>
                                </div>
                            </div>

                            <div class="panel-body">
                                <ul class="list-group">
                                    <?php foreach ($items1 as $item1): ?>
                                        <li class="list-group-item">
                                            <span class="badge">Subtotal: <br><?php echo $item1->getSubtotal(); ?> BsF</span>
                                            <p class="text-left"><?php echo $item1->getCantidad(); ?> <?php echo $item1->getUnidmedprod(); ?> de <?php echo $item1->getNombproducto(); ?></p>
                                        </li>

                                    <?php endforeach; ?>
                                </ul>
                            </div>

                            <div class="panel-footer">
                                <div class="row text-center">
                                    <?php $urlpanel1 = $this->url('despacho') ?>
                                    <form id="form-panel1" action="<?php echo $urlpanel1; ?>" method="post">

                                        <input type="hidden" name="idpedido1" value="<?= $this->idpedido1 ?>">
                                        <input type="hidden" name="idpedido2" value="<?= $this->idpedido2 ?>">
                                        <input type="hidden" name="idpedido3" value="<?= $this->idpedido3 ?>">
                                        <input type="hidden" name="idpedido4" value="<?= $this->idpedido4 ?>">
                                        <input type="hidden" name="panel1" value="<?= $this->panel1 ?>">
                                        <input type="hidden" name="panel2" value="<?= $this->panel2 ?>">
                                        <input type="hidden" name="panel3" value="<?= $this->panel3 ?>">
                                        <input type="hidden" name="panel4" value="<?= $this->panel4 ?>">
                                        <input type="hidden" name="idfinalizado" value="panel1">
                                        <input class="btn btn-default" type="submit" name="submit" value="Descartar">
                                        <input class="btn btn-danger" type="submit" name="submit" value="Eliminar">
                                        <input class="btn btn-primary" type="submit" name="submit" value="Finalizar">
                                    </form>
                                    </div>
                                <div class="row text-center text-info">Atendido por: <?php echo utf8_encode($usuarios[0]->getDisplayName()) ?></div>
                            </div>
                        </div>

                    <?php endif ?>
                </div>

                <div class="col-sm-6 col-md-6">
                    <?php if (isset($pedido2) && $panel2 === 'Ocupado') : ?>
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <div class="row">

                                    <div class="col-sm-6 col-md-8 text-center text-uppercase ">
                                        <strong>Pedido: <?php echo $pedido2->getCodigo(); ?> <br>
                                            Cliente: <?php echo $pedido2->getCliente(); ?></strong>
                                    </div>

                                    <div class="col-sm-6 col-md-4">
                                        <strong>Precio Total: <?php echo $pedido2->getPreciototal(); ?></strong>
                                    </div>
                                </div>
                            </div>

                            <div class="panel-body">
                                <div class="list-group">
                                    <?php foreach ($items2 as $item2): ?>
                                        <a href="#" class="list-group-item">
                                            <span class="badge">Subtotal: <br><?php echo $item2->getSubtotal(); ?> BsF</span>
                                            <p class="text-left"><?php echo $item2->getCantidad(); ?> <?php echo $item2->getUnidmedprod(); ?> de <?php echo $item2->getNombproducto(); ?></p>
                                        </a>

                                    <?php endforeach; ?>
                                </div>
                            </div>

                            <div class="panel-footer">
                                <div class="row text-center">
                                    <?php $urlpanel2 = $this->url('despacho') ?>
                                    <form id="form-panel2" action="<?php echo $urlpanel2; ?>" method="post">

                                        <input type="hidden" name="idpedido1" value="<?= $this->idpedido1 ?>">
                                        <input type="hidden" name="idpedido2" value="<?= $this->idpedido2 ?>">
                                        <input type="hidden" name="idpedido3" value="<?= $this->idpedido3 ?>">
                                        <input type="hidden" name="idpedido4" value="<?= $this->idpedido4 ?>">
                                        <input type="hidden" name="panel1" value="<?= $this->panel1 ?>">
                                        <input type="hidden" name="panel2" value="<?= $this->panel2 ?>">
                                        <input type="hidden" name="panel3" value="<?= $this->panel3 ?>">
                                        <input type="hidden" name="panel4" value="<?= $this->panel4 ?>">
                                        <input type="hidden" name="idfinalizado" value="panel2">
                                        <input class="btn btn-default" type="submit" name="submit" value="Descartar">
                                        <input class="btn btn-danger" type="submit" name="submit" value="Eliminar">
                                        <input class="btn btn-primary" type="submit" name="submit" value="Finalizar">
                                    </form>
                                </div>
                                <div class="row text-center text-info">Atendido por: <?php echo utf8_encode($usuarios[1]->getDisplayName()) ?></div>
                            </div>
                        </div>

                    <?php endif ?>
                </div>

            </div>

            <div class="row">

                <div class="col-sm-6 col-md-6">
                    <?php if (isset($pedido3) && $panel3 === 'Ocupado') : ?>
                        <div class="panel panel-warning">
                            <div class="panel-heading">
                                <div class="row">

                                    <div class="col-sm-6 col-md-8 text-center text-uppercase ">
                                        <strong>Pedido: <?php echo $pedido3->getCodigo(); ?> <br>
                                            Cliente: <?php echo $pedido3->getCliente(); ?></strong>
                                    </div>

                                    <div class="col-sm-6 col-md-4">
                                        <strong>Precio Total: <?php echo $pedido3->getPreciototal(); ?></strong>
                                    </div>
                                </div>
                            </div>

                            <div class="panel-body">
                                <div class="list-group">
                                    <?php foreach ($items3 as $item3): ?>
                                        <a href="#" class="list-group-item">
                                            <span class="badge">Subtotal: <br><?php echo $item3->getSubtotal(); ?> BsF</span>
                                            <p class="text-left"><?php echo $item3->getCantidad(); ?> <?php echo $item3->getUnidmedprod(); ?> de <?php echo $item3->getNombproducto(); ?></p>
                                        </a>

                                    <?php endforeach; ?>
                                </div>
                            </div>

                            <div class="panel-footer">
                                <div class="row text-center">
                                    <?php $urlpanel3 = $this->url('despacho') ?>
                                    <form id="form-panel1" action="<?php echo $urlpanel3; ?>" method="post">

                                        <input type="hidden" name="idpedido1" value="<?= $this->idpedido1 ?>">
                                        <input type="hidden" name="idpedido2" value="<?= $this->idpedido2 ?>">
                                        <input type="hidden" name="idpedido3" value="<?= $this->idpedido3 ?>">
                                        <input type="hidden" name="idpedido4" value="<?= $this->idpedido4 ?>">
                                        <input type="hidden" name="panel1" value="<?= $this->panel1 ?>">
                                        <input type="hidden" name="panel2" value="<?= $this->panel2 ?>">
                                        <input type="hidden" name="panel3" value="<?= $this->panel3 ?>">
                                        <input type="hidden" name="panel4" value="<?= $this->panel4 ?>">
                                        <input type="hidden" name="idfinalizado" value="panel3">
                                        <input class="btn btn-default" type="submit" name="submit" value="Descartar">
                                        <input class="btn btn-danger" type="submit" name="submit" value="Eliminar">
                                        <input class="btn btn-primary" type="submit" name="submit" value="Finalizar">
                                    </form>
                                </div>
                                <div class="row text-center text-info">Atendido por: <?php echo utf8_encode($usuarios[2]->getDisplayName()) ?></div>
                            </div>
                        </div>

                    <?php endif ?>
                </div>

                <div class="col-sm-6 col-md-6">
                    <?php if (isset($pedido4) && $panel4 === 'Ocupado') : ?>
                        <div class="panel panel-danger">
                            <div class="panel-heading">
                                <div class="row">

                                    <div class="col-sm-6 col-md-8 text-center text-uppercase ">
                                        <strong>Pedido: <?php echo $pedido4->getCodigo(); ?> <br>
                                            Cliente: <?php echo $pedido4->getCliente(); ?></strong>
                                    </div>

                                    <div class="col-sm-6 col-md-4">
                                        <strong>Precio Total: <?php echo $pedido4->getPreciototal(); ?></strong>
                                    </div>
                                </div>
                            </div>

                            <div class="panel-body">
                                <div class="list-group">
                                    <?php foreach ($items4 as $item4): ?>
                                        <a href="#" class="list-group-item">
                                            <span class="badge">Subtotal: <br><?php echo $item4->getSubtotal(); ?> BsF</span>
                                            <p class="text-left"><?php echo $item4->getCantidad(); ?> <?php echo $item4->getUnidmedprod(); ?> de <?php echo $item4->getNombproducto(); ?></p>
                                        </a>

                                    <?php endforeach; ?>
                                </div>
                            </div>

                            <div class="panel-footer">
                                <div class="row text-center">
                                    <?php $urlpanel4 = $this->url('despacho') ?>
                                    <form id="form-panel2" action="<?php echo $urlpanel4; ?>" method="post">

                                        <input type="hidden" name="idpedido1" value="<?= $this->idpedido1 ?>">
                                        <input type="hidden" name="idpedido2" value="<?= $this->idpedido2 ?>">
                                        <input type="hidden" name="idpedido3" value="<?= $this->idpedido3 ?>">
                                        <input type="hidden" name="idpedido4" value="<?= $this->idpedido4 ?>">
                                        <input type="hidden" name="panel1" value="<?= $this->panel1 ?>">
                                        <input type="hidden" name="panel2" value="<?= $this->panel2 ?>">
                                        <input type="hidden" name="panel3" value="<?= $this->panel3 ?>">
                                        <input type="hidden" name="panel4" value="<?= $this->panel4 ?>">
                                        <input type="hidden" name="idfinalizado" value="panel4">
                                        <input class="btn btn-default" type="submit" name="submit" value="Descartar">
                                        <input class="btn btn-danger" type="submit" name="submit" value="Eliminar">
                                        <input class="btn btn-primary" type="submit" name="submit" value="Finalizar">
                                    </form>
                                </div>
                                <div class="row text-center text-info">Atendido por: <?php echo utf8_encode($usuarios[3]->getDisplayName()) ?></div>
                            </div>
                        </div>

                    <?php endif ?>
                </div>

            </div>

        </div>

    </div>
</div>





