<?php echo $this->headScript()->appendFile($this->basePath().'/js/modules/productos/actualizar-precios.js'); ?>
<?php
$form->setAttribute('action', $this->url('my-form'))
    ->prepare();

echo $this->form()->openTag($form);

$product = $form->get('product');

?>
<div class="well">
    <?php
    echo $this->formRow($form->get('categoria'));
    echo $this->formRow($form->get('marca'));
    ?>
</div>

<div class="well">

    <div id="productos">
    <?php
    echo $this->formCollection($product->get('collection'));
    ?>
    </div>
</div>


<div class="well">
    <a href="<?php echo $this->url('application/default',array('controller' => 'index', 'action' => 'admin')); ?>" class="btn btn-default">Volver</a>
    <?php
    echo $this->formElement($form->get('submit'));

    echo $this->form()->closeTag();
    ?>
</div>




