<?php
$title = 'Listado de Pedidos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('categoria', array('action'=>'add'));?>">Crear Nuevo Producto</a></p>

<div class="row">
    <?php foreach ($this->categorias as $categoria ): ?>

        <div class="col-sm-4 col-md-3">
            <a href="<?php echo $this->url('categoria', array('action'=>'edit', 'id' => $categoria->getId()));?>">
                <div class="thumbnail">
                    <img src="<?= $categoria->getImagen() ?>" alt="<?= $categoria->getNombre() ?>">
                    <div class="caption">
                        <h3 id="categoria<?= $categoria->getId() ?>"><?= $categoria->getNombre() ?></h3>
                    </div>
                </div>
            </a>
        </div>

    <?php endforeach ?>
</div>
