<?php
$title = 'Seleccione la Categoria';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <?php foreach ($this->categorias as $categoria ): ?>

        <div class="col-sm-4 col-md-3">
            <?php $urlcat = $categoria->getId(); ?>
                 <a href="<?php echo $this->url($urlroute, array(
                    'action'=>$urlaction,
                    'id' => $urlid,
                    'cat' => $urlcat,
                    'det' => $urldet,
                    'may' => $urlmay

                ));?>">
                <div class="thumbnail">
                    <img src="<?= $categoria->getImagen() ?>" alt="<?= $categoria->getNombre() ?>">
                    <div class="caption">
                        <h3 id="categoria<?= $categoria->getId() ?>"><?= $categoria->getNombre() ?></h3>
                    </div>
                </div>
            </a>
        </div>

    <?php endforeach ?>
</div>