<?php
$title = 'Items del Pedido';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h3>Código del Pedido: <td><?php echo $pedido->getCodigo(); ?></h3>
    </div>
    <div class="col-sm-6 col-md-6">
        <h3>Cliente: <td><?php echo $pedido->getCliente(); ?></h3>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>Cantidad</th>
            <th>Unidad Medida</th>
            <th>Producto</th>
            <th>Subtotal</th>
        </tr>
        <?php foreach ($items as $item): ?>
            <tr>
                <td><?php echo $item->getCantidad(); ?></td>
                <td><?php echo $item->getUnidmedprod(); ?></td>
                <td><?php echo $item->getNombproducto(); ?></td>
                <td><?php echo $item->getSubtotal(); ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h2>Estatus: <td><?php echo $pedido->getMsgclientes(); ?></h2>
    </div>
    <div class="col-sm-6 col-md-6 text-left">
        <h3>Total: <td><?php echo $pedido->getPreciototal(); ?></h3>
    </div>
</div>