<?php
$title = 'Eliminar Almacen';
$this->headTitle($title);
?>



<div class="row">
    <div class="col-sm-3 col-md-3"></div>
    <div class="col-sm-6 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading"><h1><?php echo $this->escapeHtml($title); ?></h1></div>
            <div class="panel-body">
                <p>Está seguro que desea eliminar el almacén:
                    '<?php echo $this->escapeHtml($almacen->getNombre()); ?>' ?
                </p>
            </div>
            <div class="panel-footer">
                <?php
                $url = $this->url('almacen', array('action' => 'delete', 'id'=>$id)); ?>
                <form action="<?php echo $url; ?>" method="post">
                    <div>
                        <input class="btn btn-danger" type="submit" name="del" value="Si" />
                        <input class="btn btn-primary" type="submit" name="del" value="No" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-3 col-md-3"></div>
</div>




