<?php
$title = 'Listado de Productos';
$this->headTitle($title);
?>
<div class="row"><h1><?php echo $this->escapeHtml($title); ?></h1></div>

<div class="panel panel-primary">
    <div class="panel-heading text-center">
        <h3>Seleccione Marca</h3>
        <div class="row">


        </div>
    </div>
    <div class="panel-body text-center">
        <div class="row">
            <h3>Productos Disponibles</h3>
        </div>
        <div class="row well text-center">


                <div class="col-sm-12 col-md-12">

                    <form action="">
                        <table class="table text-center">
                            <thead>
                            <tr>
                                <th class="text-center">Marca</th>
                                <th class="text-center">Id</th>
                                <th class="text-center">Producto</th>
                                <th class="text-center">Precio</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($productos as $producto ): ?>
                            <tr>
                                <td><?= $producto->getNombMarca() ?></td>
                                <td><?= $producto->getId() ?></td>
                                <td><?= $producto->getNombre() ?></td>
                                <td><input type="text" value="<?= $producto->getPrecioUnidad() ?>">BsF.</td>
                            </tr>
                            <?php endforeach ?>
                            </tbody>
                        </table>
                    </form>

                </div>


        </div>
    </div>
    <div class="panel-footer text-right"></div>
</div>





