<?php
$title = 'Editar Producto';
$this->headTitle($title);
?>

<div class="panel panel-primary">
    <div class="panel-heading text-center"><h3><?php echo $this->escapeHtml($title); ?></h3></div>
    <div class="panel-body">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('producto', array('action' => 'edit','id' => $id, 'cat' => $cat, 'det' => $det, 'may' => $may)));
        $form->get('submit')->setAttribute('value', 'Editar Producto');
        $formLabel = $this->plugin('formLabel');
        $form->prepare();
        ?>
        <?php echo $this->form()->openTag($form); ?>

        <?php echo $this->formHidden($form->get('id'));?>
        <?php echo $this->formHidden($form->get('idcategoria')); ?>
        <?php echo $this->formHidden($form->get('idmarca')); ?>
        <?php echo $this->formHidden($form->get('unidadmedidaventas')); ?>
        <?php echo $this->formHidden($form->get('unidadmedidaalmacen')); ?>

        <div class="row">
            <div class="col-sm-6 col-md-6 well">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('nombcategoria')); ?>
                    <p><a href="<?php echo $this->url('categoria', array('action'=>'select'));?>">Seleccionar Categoria</a></p>
                </div>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('nombmarca')); ?>
                    <p><a href="<?php echo $this->url('categoria', array('action'=>'select'));?>">Seleccionar Marca</a></p>
                </div>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('nombunidmedventas')); ?>
                    <p><a href="<?php echo $this->url('unidad-medida', array('action'=>'select','id' => $id, 'tipo' => 'det'));?>">Seleccionar Unidad de Medida</a></p>
                </div>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('nombunidmedalmacen')); ?>
                    <p><a href="<?php echo $this->url('unidad-medida', array('action'=>'select','id' => $id, 'tipo' => 'may'));?>">Seleccionar Unidad de Medida</a></p>
                </div>
            </div>

            <div class="col-sm-6 col-md-6">
                <div class="form-group">
                    <?php echo $this->formRow($form->get('nombre')); ?>
                </div>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('preciounidad')); ?>
                </div>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('relacionunidad')); ?>
                </div>

                <div class="form-group">
                    <?php echo $this->formRow($form->get('imagen')); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer text-right">
        <a href="<?php echo $this->url('producto') ?>" class="btn btn-default">Volver</a>
        <?php echo $this->formInput($form->get('submit')); ?>
    </div>
    <?php echo $this->form()->closeTag($form); ?>
</div>