<?php
$title = 'Listado de Productos';
$this->headTitle($title);
?>
<div class="row"><h1><?php echo $this->escapeHtml($title); ?></h1></div>

<div class="panel panel-primary">
    <div class="panel-heading text-center">
        <h3>Seleccione Categoría</h3>
        <div class="row">

            <form id="my_form" action="<?php $this->url('producto'); ?>" method="post">
                <ol class="breadcrumb">
                    <input type="hidden" name="Todos" value="0" />
                    <li class="active"><input type="submit" class="btn btn-primary" name="selcat" value="Todos" /></li>
                    <?php foreach ($categorias as $categoria ): ?>
                        <input type="hidden" name="<?php echo $categoria->getNombre() ?>" value="<?php echo $categoria->getId() ?>" />
                        <li><input type="submit" class="btn btn-info" name="selcat" value="<?php echo $categoria->getNombre() ?>" /></li>
                    <?php endforeach ?>
                </ol>

            </form>

        </div>
    </div>
    <div class="panel-body text-center">
        <div class="row">
            <div class="col-sm-6 col-md-6"><h3>Productos Disponibles</h3></div>
            <div class="col-sm-6 col-md-6">
                <?php echo $this->paginationControl($this->paginator,'sliding','partial/paginator.phtml',array('route' => 'producto')); ?>
            </div>

        </div>
        <div class="row well text-center">
            <?php foreach ($paginator as $producto ): ?>

                <div class="col-sm-6 col-md-2">
                    <a href="<?php echo $this->url('producto', array('action'=>'editar-producto', 'id' => $producto->getId()));?>" class="thumbnail">
                        <?php if (($producto->getModificado() !== '0000-00-00') && (((floor(abs(strtotime($producto->getModificado())-strtotime(date('Y-m-d')))))/86400) < 5)) :?>
                            <div class="ribbon orange"><span>Actualizado</span></div>
                        <?php endif ?>
                        <?php if ($producto->getDisponible() !== '1')  :?>
                            <div class="ribbon red"><span>Agotado</span></div>
                        <?php endif ?>

                            <img src="<?= $producto->getImagen() ?>" alt="<?= $producto->getNombre() ?>">
                            <div class="caption">
                                <h4 id="producto<?= $producto->getId() ?>"><?= $producto->getNombre() ?></h4>
                                <p>Categoría:<?= $producto->getNombcategoria() ?></p>
                                <p>Precio:<?= $producto->getPreciounidad() ?> BsF por  <?= $producto->getNombunidmedventas() ?></p>
                            </div>
                    </a>
                </div>

            <?php endforeach ?>
        </div>

    </div>
    <div class="panel-footer text-right">
        <a href="<?php echo $this->url('application/default',array('controller' => 'index', 'action' => 'admin')); ?>" class="btn btn-default">Volver</a>
        <a href="<?php echo $this->url('producto', array('action'=>'crear-producto'));?>" class="btn btn-primary">Crear Nuevo Producto</a>
    </div>
</div>





