<?php echo $this->headScript()->appendFile($this->basePath().'/js/highcharts/highcharts.js'); ?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/highcharts/highcharts-3d.js'); ?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/highcharts/modules/exporting.js'); ?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/highcharts/modules/heatmap.js'); ?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/reportes/combo.js'); ?>

<div id="container" style="width:100%; height:400px;"></div>