<?php echo $this->headScript()->appendFile($this->basePath().'/js/highcharts/highcharts.js'); ?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/highcharts/highcharts-3d.js'); ?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/highcharts/modules/exporting.js'); ?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/highcharts/modules/heatmap.js'); ?>
<?php echo $this->headScript()->appendFile($this->basePath().'/js/reportes/pedidos-x-despachador.js'); ?>

<div id="container"></div>
