<?php
$title = 'Seleccione el Almacén';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <?php foreach ($this->almacenes as $almacen ): ?>

        <div class="col-sm-4 col-md-3">
            <?php $urlidmayor = $almacen->getId(); ?>
            <a href="<?php echo $this->url($urlroute, array(
                'action'=>$urlaction,
                'idmayor' => $urlidmayor,
                'iddetal' => $urliddetal,
                'idproducto' => $urlidproducto,
            ));?>">
                <div class="thumbnail">
                    <div class="caption">
                        <h3 id="almacen<?= $almacen->getId() ?>"><?= $almacen->getNombre() ?></h3>
                    </div>
                </div>
            </a>
        </div>

    <?php endforeach ?>
</div>