<h1>Productos\ProductosController::indexAction()</h1>
<div class="row">
<?php foreach ($this->productos as $producto ): ?>

    <div class="col-sm-4 col-md-3">
        <a href="#">
        <div class="thumbnail">
            <img src="<?= $producto->getImagen() ?>" alt="<?= $producto->getNombre() ?>">
            <div class="caption">
                <h3 id="producto<?= $producto->getId() ?>"><?= $producto->getNombre() ?></h3>
                <p>Categoría:<?= $producto->getCategoria() ?></p>
                <p>Precio:<?= $producto->getPrecioUnidad() ?> BsF por  <?= $producto->getUnidadMedidaVentas() ?></p>
                
            </div>
        </div>
        </a>
    </div>

<?php endforeach ?>
</div>
