<div class="row">
    <div class="col-sm-2 col-md-2"></div>
    <div class="col-sm-8 col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading"><h2 class="text-center">Inventario de Productos Disponibles en <?php echo $almacen->getNombre(); ?></h2></div>
            <div class="panel-body">

                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Cantidad Disponible</th>
                            <th>Unidad Medida</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($disponibilidadAlmacen as $da): ?>
                            <tr>
                                <td><?php echo $da->getNombproducto(); ?></td>
                                <td><?php echo $da->getDisponible(); ?></td>
                                <td><?php echo $da->getUnidmed(); ?></td>
                            </tr>
                        <?php endforeach ?>
                        </tbody>
                    </table>

            </div>
            <div class="panel-footer">
                <a href="<?php echo $this->url('reportes') ?>" class="btn btn-default">Volver</a>
            </div>
        </div>
    </div>
    <div class="col-sm-2 col-md-2"></div>
</div>