<div class="row">
    <div class="col-sm-2 col-md-2"></div>
    <div class="col-sm-8 col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading"><h2 class="text-center">Historial de Ingresos de Productos en <?php echo $almacen->getNombre(); ?></h2></div>
            <div class="panel-body">

                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Fecha</th>
                        <th>Producto</th>
                        <th>Cantidad Ingresada</th>
                        <th>Unidad Medida</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($ingresos as $in): ?>
                        <tr>
                            <td><?php echo $in->getFecha(); ?></td>
                            <td><?php echo $in->getNombproducto(); ?></td>
                            <td><?php echo $in->getCantidad(); ?></td>
                            <td><?php echo $in->getUnidmed(); ?></td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>

            </div>
            <div class="panel-footer">
                <a href="<?php echo $this->url('almacen') ?>" class="btn btn-default">Volver</a>
            </div>
        </div>
    </div>
    <div class="col-sm-2 col-md-2"></div>
</div>