<h1>Categorias\ListarController::indexAction()</h1>
<div class="row">
<?php foreach ($this->categorias as $categoria ): ?>

    <div class="col-sm-4 col-md-3">
        <a href="categorias/editar/<?= $categoria->getId() ?>">
        <div class="thumbnail">
            <img src="<?= $categoria->getImagen() ?>" alt="<?= $categoria->getNombre() ?>">
            <div class="caption">
                <h3 id="categoria<?= $categoria->getId() ?>"><?= $categoria->getNombre() ?></h3>
            </div>
        </div>
        </a>
    </div>

<?php endforeach ?>
</div>
