<!-- Filename: /module/Blog/view/blog/delete/delete.phtml -->
<h1>DeleteController::deleteAction()</h1>
<p>
    Are you sure that you want to delete
    '<?php echo $this->escapeHtml($this->post->getTitle()); ?>' by
    '<?php echo $this->escapeHtml($this->post->getText()); ?>'
</p>
<form action="<?php echo $this->url('blog/delete', array(), true) ?>" method="post">
    <input type="submit" value="yes" name="delete_confirmation">
    <input type="submit" value="no" name="delete_confirmation">
</form>