<?php
$title = 'Listado de Unidades de Medidas';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('unidad-medida', array('action'=>'add'));?>">Crear Nueva Unidad de Medida</a></p>

<div class="row">
    <?php foreach ($this->unidadesMedida as $unidadMedida ): ?>

        <div class="col-sm-4 col-md-3">
            <a href="<?php echo $this->url('unidad-medida', array('action'=>'edit', 'id' => $unidadMedida->getId()));?>">
            <div class="thumbnail">
                <div class="caption">
                    <h3 id="unidadMedida<?= $unidadMedida->getId() ?>"><?= $unidadMedida->getNombre() ?></h3>
                    <p>Abreviatura:<?= $unidadMedida->getAbreviatura() ?></p>
                    <p>Símbolo:<?= $unidadMedida->getSimbolo() ?></p>
                </div>
            </div>
            </a>
        </div>

    <?php endforeach ?>
</div>
