<div class="jumbotron text-center">
    <h1><?php echo $this->escapeHtml($this->unidadMedida->getNombre()); ?></h1>
</div>

<div class="row marketing text-center">
    <div class="col-lg-6">
        <h4>Abreviatura</h4>
        <p><?php echo $this->escapeHtml($this->unidadMedida->getAbreviatura()); ?></p>
    </div>

    <div class="col-lg-6">
        <h4>Símbolo</h4>
        <p><?php echo $this->escapeHtml($this->unidadMedida->getSimbolo()); ?></p>
    </div>
</div>