<div class="row well well-sm text-center text-primary">
    <h1>Sistema de Pedidos Ares</h1>
</div>

<div class="jumbotron">

    <div class="row placeholders">

        <div class="col-xs-6 col-sm-6 col-md-6 placeholder">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Módulo de Administración</h3>
                </div>
                <div class="panel-body text-center">
                    <i class="icon-settingsthree-gears" style="font-size: 100px; "></i>
                    <div class="btn-toolbar">
                        <div class="btn-group btn-group-sm" role="group">
                            <a class="btn btn-default" href="<?php echo $this->url('producto');?>" >Productos</a>
                            <a class="btn btn-default" href="<?php echo $this->url('categoria');?>" >Categorias</a>
                            <a class="btn btn-default" href="<?php echo $this->url('unidad-medida');?>" >Unid/Medida</a>
                        </div>
                        <div class="btn-group btn-group-sm" role="group">
                            <a class="btn btn-default" href="<?php echo $this->url('almacen');?>" >Almacén</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-xs-6 col-sm-6 col-md-6 placeholder">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Módulo de Reportes</h3>
                </div>
                <div class="panel-body text-center">
                    <i class="icon-analytics-piechart" style="font-size: 100px; "></i>
                    <div class="btn-toolbar">
                        <div class="btn-group" role="group">
                            <a class="btn btn-default pull-right" href="<?php echo $this->url('producto');?>" >Listado de Productos</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>



</div>

<div class="row well well-sm text-center">
    <br><br><br>
</div>
