<div class="row well well-sm text-center text-primary">
    <h1>Sistema de Pedidos Ares</h1>
</div>

<div class="container">

    <form class="form-signin">
        <h2 class="form-signin-heading">Login</h2>
        <label for="inputEmail" class="sr-only">Nombre de Usuario</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Nombre de Usuario" required autofocus>
        <label for="inputPassword" class="sr-only">Contraseña</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Contraseña" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" value="remember-me"> Recordarme
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Autentificarse</button>
    </form>

</div> <!-- /container -->

<div class="row well well-sm text-center">
    <br><br><br>
</div>