<div class="row well well-sm text-center text-primary">
    <h1>Sistema de Pedidos Ares</h1>
</div>

<div class="jumbotron">
    <div class="row placeholders">

        <div class="col-xs-6 col-sm-4 col-md-4 placeholder">
            <a href="<?php echo $this->url('pedido');?>">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Módulo de Ventas</h3>
                    </div>
                    <div class="panel-body text-center">
                        <i class="icon-addtocart" style="font-size: 100px; "></i>
                    </div>
                </div>
            </a>
        </div>


        <div class="col-xs-6 col-sm-4 col-md-4 placeholder">
            <a href="<?php echo $this->url('despacho');?>">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Módulo de Despacho</h3>
                    </div>
                    <div class="panel-body text-center">
                        <i class="icon-cartalt" style="font-size: 100px; "></i>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-xs-6 col-sm-4 col-md-4 placeholder">
            <a href="#">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Módulo de Clientes</h3>
                    </div>
                    <div class="panel-body text-center">
                        <i class="icon-groups-friends" style="font-size: 100px; "></i>
                    </div>
                </div>
            </a>
        </div>

    </div>

</div>

<div class="row well well-sm text-center">
    <br><br><br>
</div>
