<div class="row well well-sm text-center text-primary">
    <h1>Sistema de Pedidos Ares</h1>
</div>

<div class="container">



            <div class="container">
                <div class="row">

                    <div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
                    <h3><?php echo $this->translate('Hello'); ?>, <?php echo utf8_encode($this->zfcUserDisplayName()) ?>!</h3>
                    <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
                </div>
            </div>


    <div class="row well well-sm text-center">
        <br><br><br>
    </div>




