<div class="row well well-sm text-center text-primary">
    <h1>Sistema de Pedidos Ares</h1>
</div>

<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-signin');
?>

<div class="row">
    <div class="col-sm-3 col-md-3"></div>
    <div class="col-sm-6 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading text-center">
                <h1><?php echo $this->translate('Registro de Usuario'); ?></h1>
            </div>
            <div class="panel-body">

                <?php echo $this->form()->openTag($form) ?>
                <?php foreach ($form as $element) : ?>

                    <div style="width: 330px;" class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                        <?php
                        if ('submit' != $element->getAttribute('type')) { ?>
                            <label class="control-label"><?php echo $this->translate($element->getLabel()) ?></label>
                            <?php
                            $element->setAttribute('class', 'form-control')
                                ->setAttribute('placeholder', $element->getLabel());
                        } else {
                            $element->setAttribute('class', 'btn btn-lg btn-primary btn-block');
                        }
                        if ($element instanceof Zend\Form\Element\Captcha) {
                            echo $this->formCaptcha($element);
                        } else {
                            echo $this->formElement($element);
                        }
                        if ($this->formElementErrors($element)) : ?>
                            <?php
                            echo $this->formElementErrors()
                                ->setMessageOpenFormat('<p class="help-block">')
                                ->setMessageSeparatorString('</p><p class="help-block">')
                                ->setMessageCloseString('</p>')
                                ->render($element);
                            ?>
                        <?php endif; ?>
                    </div>

                    <?php
                endforeach;
                if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php endif ?>
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
    <div class="col-sm-3 col-md-3"></div>
</div>



<div class="row well well-sm text-center">
    <br><br><br>
</div>